name: Lint and Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest]

    steps:
      - name: Disable Auto CRLF
        run: git config --global core.autocrlf false

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use pnpm v7
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:ci
